# Generated by Django 5.0.6 on 2024-05-18 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StandartOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_detail', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='service/images/%Y/%m/%d/')),
                ('options', models.ManyToManyField(to='web.detailsoption')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.serviceoption')),
                ('standard_equipment', models.ManyToManyField(to='web.standartoption')),
            ],
        ),
    ]
