# Generated by Django 5.0.6 on 2024-05-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='collectionsmodel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='contactusmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='LogoModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='ProjectsModel',
        ),
        migrations.DeleteModel(
            name='CollectionsCategoryModel',
        ),
        migrations.DeleteModel(
            name='CollectionsModel',
        ),
        migrations.DeleteModel(
            name='ContactUSModel',
        ),
    ]
