# Generated by Django 4.2.1 on 2023-05-28 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Collections category',
                'verbose_name_plural': 'Collections categories',
            },
        ),
        migrations.CreateModel(
            name='CollectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('collection_image', models.ImageField(upload_to='collection/%Y/%m/%d/')),
                ('collection_info', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='web.collectionscategorymodel', verbose_name='category')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('-id',),
            },
        ),
    ]
