# Generated by Django 4.2.1 on 2023-05-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_collectionscategorymodel_collectionsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionsmodel',
            options={'ordering': ('-id',), 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
    ]
