# Generated by Django 4.2.1 on 2023-05-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_collectionsmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Projects category', 'verbose_name_plural': 'Projects categories'},
        ),
    ]
