# Generated by Django 5.0.6 on 2024-05-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_contactmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'ordering': ['-id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
