# Generated by Django 5.0.6 on 2024-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_servicemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('preview_image', models.ImageField(upload_to='ourwork/preview/%Y/%m/%d/')),
                ('short_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Our work',
                'verbose_name_plural': 'Our works',
                'ordering': ['-id'],
            },
        ),
    ]
