# Generated by Django 4.2.1 on 2023-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_categorymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionsmodel',
            name='collection_second_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='project_second_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/'),
        ),
    ]
