# Generated by Django 5.0.6 on 2024-05-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_ourworksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourworksmodel',
            name='extra_image',
            field=models.ImageField(blank=True, null=True, upload_to='ourwork/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ourworksmodel',
            name='extra_image_second',
            field=models.ImageField(blank=True, null=True, upload_to='ourwork/images/%Y/%m/%d/'),
        ),
    ]
