# Generated by Django 4.2.1 on 2023-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_collectionsmodel_collection_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsmodel',
            name='collection_info',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='project_info',
            field=models.TextField(max_length=300),
        ),
    ]
